apiVersion: skaffold/v2beta26
kind: Config
metadata:
  name: go-echo
build:
  tagPolicy:
    dateTime:
      format: "2006-01-02_15-04-05.999_DST"
      timezone: "Local"
  artifacts:
  - image: us-central1-docker.pkg.dev/mchirico/public/goecho
    ko: {}

